FROM debian:stretch-slim

RUN apt-get update -y \
	&& apt-get install -y  --no-install-recommends ca-certificates=20200601~deb9u2 curl=7.52.1-5+deb9u15 \
    && rm -rf /var/lib/apt/lists/*
COPY CA_crt.pem /usr/local/share/ca-certificates/CA_crt.crt
RUN update-ca-certificates --fresh